### PR TITLE
Removing HP from documentation

### PR DESCRIPTION
**Pull request by jjasghar**
- This removes and makes note of the HP Public cloud being shutdown.

### CODE REVIEW

**Comment by geemus** [comment]
Thanks!

**Comment by rupakg** [comment]
Sad to see it go :(

**Comment by geemus** [comment]
@rupakg yeah, thanks again for all your help along the way.

**Comment by rupakg** [comment]
@geemus Thanks, it was great working with you and the awesome Fog contributors. I will keep an eye on the progress.

**Pull request merged**
