### PR TITLE
Adding LICENSE.md from fog repo

### PR DESCRIPTION
**Pull request by erjohnso**
Hi folks,

I'm hoping you'll be amenable to adding a copy of your LICENSE file from the main fog repo to your docs repo. We'd like to contribute a few pull-requests to the docs in this repo and our legal time strongly prefers the presence of a license file exist before we can contribute.

Thanks for considering!

/cc @icco

### CODE REVIEW

**Comment by tokengeek** [comment]
I think it's fine @geemus ?

**Comment by icco** [comment]
Man @erjohnso, doing the right thing... I was always a "It's easier to ask for forgiveness" kind of guy :p

**Comment by erjohnso** [comment]
@icco - yes. And I always drive the speed limit too.

Hope all is well with you! FYI - I'm going to try signing you up for a couple Q2 OKRs... not sure if the tool will let me, but I'm going to try anyway.

**Comment by geemus** [comment]
Definitely cool, as you might imagine, this was simply an oversight.

**Comment by erjohnso** [comment]
Thanks @geemus! @ihmccreery, unleash the hounds!

**Pull request merged**
