### PR TITLE
Add CenturyLink

### PR DESCRIPTION
**Pull request by ack**
Hi! Would like to include our padawan driver into the provider page.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@ack Nice. But it seems `centurylink` is not supported yet.

Check it [here](https://github.com/fog/fog/blob/master/fog.gemspec#L53-L77)

**Comment by ack** [comment]
I wasn't sure what protocol is these days for inclusion. When I went looking around, it seems that the process for 3rd party plugins is in flight ATM. I'm happy to open up a PR against fog for the gemspec change, but there are no tests in this plugin, not sure it conforms to fog conventions, etc. As it stands the plugin is intended to be used as an external plugin mixed into the Fog namespace. Thoughts?

**Comment by plribeiro3000** [comment]
The idea is that the source needs to be under `fog` organization and at least @geemus need to have access to release into `rubygems` (in case of emergency). 

Tests are for sure something we need (So we are sure we are not breaking everything)
And we need to check if the code is following our latest conventions (avoid loading everything at startup to improve performance)

Can you check those things above as a start point?

After we got everything right, we can push it as a dependency of `fog` and into here.

**Comment by geemus** [comment]
Yeah, what @plribeiro3000 outlines sounds great. Happy to discuss/help as needed.

**Comment by plribeiro3000** [comment]
Since centurylink is not supported yet i'm closing this.

You can check which providers are getting supported at fog/fog#3644

Thanks!

**Pull request closed without merging**
