### PR TITLE
Add CarrierWave Storage integration example

### PR DESCRIPTION
**Pull request by Temikus**
@plribeiro3000 @geemus PTAL

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@Temikus Since `carrierwave` depends on `fog` wouldn't this be a better fit at its [`README`](https://github.com/carrierwaveuploader/carrierwave#using-google-storage-for-developers)?

Its README is outdated.

**Comment by Temikus** [comment]
Ah, fair enough, I'll take a look in there. Though I did get a request to put it explicitly into Fog.io docs: https://github.com/fog/fog-google/issues/385

I'll defer on your judgement whether to put it in here or not.

P.S. Long time - no see :)

**Comment by geemus** [comment]
Hey, nice to see you again!

Adding these docs sounds good, but it does sound to me like it would fit most obviously in the carrierwave docs (or barring that, in fog-google docs). It seems overly specific to be in the overaching docs I think, since it would only be relevant to a smaller subset of users.

Thanks!

**Comment by Temikus** [comment]
Cool, added to CarrierWave: https://github.com/carrierwaveuploader/carrierwave/pull/2502

Nice to see you too :) Hope we get a chance to see each-other in person again sometime!

**Comment by geemus** [comment]
Thanks, yeah that sounds great!

**Pull request closed without merging**
